[phases.setup]
nixPkgs = ["php82", "composer", "nodejs", "npm"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"